language: php

php:
  - '7.4'
  - '7.3'
  - '7.2'
  - '7.1'
  - '7.0'
  - '5.6'

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest"
    - PREFER_LOWEST=""

matrix:
  allow_failures:
    - php: '7.1'
    - php: '7.0'
    - php: '5.6'

install:
  - echo 'error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - |
    if [[ "$(phpenv version-name)" < "7.2" ]]
    then
      travis_retry composer require --no-interaction --prefer-source $PREFER_LOWEST 'phpunit/phpunit:^5.7'
    fi
  - travis_retry composer update --no-interaction --prefer-source $PREFER_LOWEST

script:
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit -v --color -c .travis-phpunit.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
